### PR TITLE
parallelize creation of build execs

### PR DESCRIPTION
**Pull request by finfinack**

### CODE REVIEW

**Comment by mre** [comment]
Thanks for the PR @finfinack.
There's a minor thing to fix before we can merge this:

```
go build
# github.com/mre/riffraff/commands
commands/build.go:34:5: too many arguments to return
	have (error)
	want ()
commands/build.go:38:5: too many arguments to return
	have (error)
	want ()
make: *** [Makefile:5: build] Error 2```

Can you take care?

**Comment by finfinack** [comment]
Sorry for missing this. This will be a bit more involved. Which of the options do you prefer?

1) Not handing back the error as it won't be easily accessible to the outside function because it happens inside the Go routine.

2) Handing back the error through an error channel. This requires some setup and makes it a bit more involved as we will also have to lease from the error channel to check whether any Go routine resulted in any problems.

3) Reverting/abandoning the PR. This depends on how much you think you gain from starting the builds in parallel I guess?

Let me know.

**Comment by mre** [comment]
I think there's not much we can do when the build can be triggered other than logging the error. So that's what I would probably do. Maybe simply logging it on info level is enough as the other builds could still be triggered. What do you think?

**Comment by finfinack** [comment]
Logging seems fine. I've opted for fmt.Printf rather than log.Printf as that seems to be used more commonly in the codebase but let me know if you prefer me changing to log instead.

**Comment by mre** [comment]
LGTM. Thanks for your contribution!

**Pull request merged**
