### PR TITLE
Feature/update readme

### PR DESCRIPTION
**Pull request by iampeterbanjo**
I started working on the tests and added some notes on how I got started with `riffraff`.

### CODE REVIEW

**Comment by iampeterbanjo** [comment]
I'm getting this error in Vscode in `find.go`. Do you know why?

```
---- Vscode terminal output Go ----
/home/iampeterbanjo/golang/src/github.com/iampeterbanjo/riffraff/job>Finished running tool: /home/iampeterbanjo/golang/bin/golint

/home/iampeterbanjo/golang/src/github.com/iampeterbanjo/riffraff/job>Finished running tool: /home/iampeterbanjo/.asdf/installs/golang/1.11.1/go/bin/go vet ./...

/home/iampeterbanjo/golang/src/github.com/iampeterbanjo/riffraff/job>Finished running tool: /home/iampeterbanjo/.asdf/installs/golang/1.11.1/go/bin/go build -o /tmp/vscode-goOqoy8F/go-code-check github.com/iampeterbanjo/riffraff/job
go: finding github.com/iampeterbanjo/riffraff/job latest
go: github.com/iampeterbanjo/riffraff@v0.3.0: parsing go.mod: unexpected module path "github.com/mre/riffraff"
go: error loading module requirements

---- in Vscode Editor find.go line 1---
go: finding github.com/iampeterbanjo/riffraff/job latest
go: finding github.com/iampeterbanjo/riffraff v0.3.0
go: downloading github.com/iampeterbanjo/riffraff v0.3.0
go: github.com/iampeterbanjo/riffraff@v0.3.0: parsing go.mod: unexpected module path "github.com/mre/riffraff"
go: error loading module requirements
```

**Comment by mre** [comment]
Haven't seen this error before, but this gives a hint:

```
go: github.com/iampeterbanjo/riffraff@v0.3.0: parsing go.mod: unexpected module path "github.com/mre/riffraff"
```

You're working on your fork so it expects `github.com/iampeterbanjo/riffraff` as the project name in the `go.mod`, but it finds my upstream version, `github.com/mre/riffraff`.

Maybe related to the Go tooling in VSCode? We should check for issues there.

Few ideas:
1. Does it work from the commandline? E.g. can you run a `make build` without any problems there?
2. If not, does it work on a clean checkout of your fork?

**Comment by iampeterbanjo** [comment]
Hmm... after a computer restart the problem seems to have gone away and `make build` works. 

Thanks.

**Comment by mre** [comment]
Thank YOU @iampeterbanjo. 😉

**Pull request merged**
