### PR TITLE
add tests for status markers

### PR DESCRIPTION
**Pull request by iampeterbanjo**
I used [GoConvey](https://github.com/smartystreets/goconvey) because it has an automatic test run on file changes plus assert library.

I looked at stubbing or mocking the [Jenkins struct](https://github.com/bndr/gojenkins/blob/master/jenkins.go#L104) but it seems like it has a bit of complexity I don't totally understand. Have you thought about how you might test this?

The status output seemed like a simple win.

### CODE REVIEW

**Comment by mre** [comment]
> I used GoConvey because it has an automatic test run on file changes plus assert library.

That looks really nice. Didn't use it before.

> Have you thought about how you might test this?

Not really. Apart from the obvious integration tests we could do, mocking the go-jenkins struct might in fact be the way to go.
Another idea is to wrap the Jenkins struct inside our own struct as `conn` and simply pass a dummy `conn` when we are testing.

```
type Jenkins struct {
  conn *gojenkins.Jenkins
}
```

But then we end up implementing the exact same methods on our custom type and we also have to copy over the structs from go-jenkins.

I'd have to think about this some more, but if you want to give it a shot, go ahead. I'm sure we'll figure something out along the way. Feedback welcome.

**Comment by mre** [comment]
Can you merge the master into your branch? There are a few conflicting files.

**Comment by iampeterbanjo** [comment]
i'm getting build errors. do you know how I can fix it?

**Comment by mre** [comment]
Huh? Works for me. All tests are passing.

Did you run `git merge origin master` and then fix the merge conflicts? Make sure that `origin` points to my repo. 😉 

You can take a look at my branch here, where I fixed the merge conflicts:
https://github.com/mre/riffraff/tree/reintegrate-master

If you like, you can also merge this branch (`git merge origin reintegrate-master`) and we should be good. 😊

**Comment by iampeterbanjo** [comment]
yay. fixed merge conflicts. thanks for your help :smile:

**Comment by mre** [comment]
Tried to fix the error with the missing package, but to no avail. If anybody has a clue what's going on, help would be much appreciated. 😉

**Comment by iampeterbanjo** [comment]
i had this issue on my computer when i was trying to use testify but the issue wasn't with testify.
https://github.com/stretchr/testify/issues/214#issuecomment-429477498

the problem is not with the dependencies but because I was using Go modules inside my $GOPATH. i moved the riffraff project out of $GOPATH and everything worked again. 

maybe we need to change something here:
```Shell
$ mkdir -p ${TRAVIS_HOME}/gopath/src/github.com/mre/riffraff
$ tar -Pczf ${TRAVIS_TMPDIR}/src_archive.tar.gz -C ${TRAVIS_BUILD_DIR} . && tar -Pxzf ${TRAVIS_TMPDIR}/src_archive.tar.gz -C ${TRAVIS_HOME}/gopath/src/github.com/mre/riffraff
$ export TRAVIS_BUILD_DIR=${TRAVIS_HOME}/gopath/src/github.com/mre/riffraff
$ cd ${TRAVIS_HOME}/gopath/src/github.com/mre/riffraff
```

**Comment by rking788** [comment]
it looks like the goconvery dependency is only defined in the modules file. So either https://github.com/mre/riffraff/pull/20 needs to be fixed/merged to add module support to the Travis build or the dependency can be declared in the Makefile temporarily.

**Comment by mre** [comment]
Yeah, I think #20 is the way to go. I was doing it wrong somehow, but I don't have time to look into it right now. Added a comment over there for things to try. If you have time, give it a shot if you like. 😉

**Comment by mre** [comment]
With #20 being merged, could you merge the master to see if the build passes now @iampeterbanjo?
@rking788, should work right?

**Comment by mre** [comment]
This was now merged after being rolled up in #34. Thanks for your contribution @iampeterbanjo. ⭐️ 
P.S.: Decided to remove the dependency on goconvey again, because it requires https://github.com/jtolds/gls, which did not build on Go master.

**Pull request closed without merging**
