### PR TITLE
Cobra

### PR DESCRIPTION
**Pull request by Muskuloese**
[WIP] A migration of the cli to [cobra](https://github.com/spf13/cobra).
- Implemented with command flags, and does not support positional arguments at the moment.

### CODE REVIEW

**Comment by mre** [comment]
Thanks for the PR. As discussed in person, I'd like to keep the support for positional arguments, e.g.
`riffraff status <regex>` should keep working.
Other than that, I'd be quite happy to switch to Cobra.

**Comment by mre** [comment]
Can you reintegrate the master and also update the `README.md` with the new help text? (https://github.com/mre/riffraff#features)

**Comment by rking788** [comment]
it might be nice to rework some of the commits included in this pull request. removing the WIP commit and combining the README update commits might make sense as well as combining any other commits that make sense.

**Comment by Muskuloese** [comment]
Looks like I duplicated the commits while trying to remove some of them. I luckily created a new branch in the process. I will close this PR and create a new one with the cleaner commits.

**Pull request closed without merging**
